default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: stock_development 
  username: stock 

test:
  <<: *default
  database: stock_test
  username: stock 

production:
  <<: *default
  database: stock_production
  username: stock 
  password: stock_pw
