default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: postgres
  username: postgres 
  password:
  host: db

test:
  <<: *default
  database: postgres
  username: postgres 
  password:
  host: db

production:
  <<: *default
  database: stock_production
  username: stock 
  password: stock_pw
